Repository Paris-Squad-S2/Tudee-App, pull requests merged in 2025-06, with the labels that each got.

#20 add task service functionality
  app/src/main/java/com/example/tudeeapp/data/TaskServicesImpl.kt
  app/src/main/java/com/example/tudeeapp/data/source/local/room/dao/CategoryDao.kt
  app/src/main/java/com/example/tudeeapp/data/source/local/room/dao/TaskDao.kt
  app/src/main/java/com/example/tudeeapp/domain/TaskServices.kt
  app/src/main/java/com/example/tudeeapp/domain/exception/TudeeException.kt
Labels: feature

#23 update the get categories name and handle exception
  app/src/main/java/com/example/tudeeapp/data/TaskServicesImpl.kt
  app/src/main/java/com/example/tudeeapp/data/source/local/room/dao/CategoryDao.kt
  app/src/main/java/com/example/tudeeapp/domain/exception/TudeeException.kt
Labels: enhancement

#9 feature/get-categories-details-screen
  app/build.gradle.kts
  app/src/main/java/com/example/tudeeapp/di/ViewModelModule.kt
  app/src/main/java/com/example/tudeeapp/presentation/common/components/HorizontalTabs.kt
  app/src/main/java/com/example/tudeeapp/presentation/common/components/TopAppBar.kt
  app/src/main/java/com/example/tudeeapp/presentation/navigation/Screens.kt
  app/src/main/java/com/example/tudeeapp/presentation/navigation/TudeeNavGraph.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoryDetails/CategoryDetailsScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoryDetails/CategoryDetailsViewModel.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoryDetails/state/CategoryDetailsUiState.kt
  app/src/main/java/com/example/tudeeapp/presentation/utills/TaskPriority.kt
  app/src/main/res/drawable/ic_pencil_edit.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature

#16 Feature/home
  .gitignore
  app/build.gradle.kts
  app/src/main/java/com/example/tudeeapp/di/ViewModelModule.kt
  app/src/main/java/com/example/tudeeapp/presentation/common/components/Slider.kt
  app/src/main/java/com/example/tudeeapp/presentation/common/components/TabItem.kt
  app/src/main/java/com/example/tudeeapp/presentation/common/components/TudeeHomeMessage.kt
  app/src/main/java/com/example/tudeeapp/presentation/common/components/TudeeNavigationBar.kt
  app/src/main/java/com/example/tudeeapp/presentation/navigation/Screens.kt
  app/src/main/java/com/example/tudeeapp/presentation/navigation/TudeeNavGraph.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoryDetails/CategoryDetailsScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/HomeScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/HomeViewModel.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/composable/HomeEmptyTaskSection.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/composable/HomeTaskCard.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/composable/HomeTaskSection.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/composable/OverviewCard.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/state/HomeUiState.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/state/SliderState.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/state/TaskUiState.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/utils/getFormattedDate.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/onBoarding/OnBoardingScreen.kt
  app/src/main/res/drawable-hdpi/img_ropo_cry.png
  app/src/main/res/drawable-hdpi/img_ropot4.png
  app/src/main/res/drawable-mdpi/img_ropo_cry.png
  app/src/main/res/drawable-mdpi/img_ropot4.png
  app/src/main/res/drawable-xhdpi/img_ropo_cry.png
  app/src/main/res/drawable-xhdpi/img_ropot4.png
  app/src/main/res/drawable-xxhdpi/img_ropo_cry.png
  app/src/main/res/drawable-xxhdpi/img_ropot4.png
  app/src/main/res/drawable-xxxhdpi/img_ropo_cry.png
  app/src/main/res/drawable-xxxhdpi/img_ropot4.png
  app/src/main/res/drawable/ic_arrow.xml
  app/src/main/res/drawable/ic_date.xml
  app/src/main/res/drawable/ic_done.xml
  app/src/main/res/drawable/ic_in_progress.xml
  app/src/main/res/drawable/ic_overview_card_background.xml
  app/src/main/res/drawable/ic_to_do.xml
  app/src/main/res/drawable/task_card_dots.png
  app/src/main/res/drawable/task_card_ropo_background.png
  app/src/main/res/drawable/task_card_ropo_container.png
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature

#33 Limit maxLines to 11 for text fields to prevent excessive input
  app/src/main/java/com/example/tudeeapp/presentation/common/components/TextFields.kt
Labels: fix

#41 refactor simplify bottom navigation bar
  app/src/main/java/com/example/tudeeapp/presentation/common/components/TudeeNavigationBar.kt
  app/src/main/java/com/example/tudeeapp/presentation/common/components/TudeeScaffold.kt
  app/src/main/java/com/example/tudeeapp/presentation/navigation/TudeeNavGraph.kt
Labels: enhancement

#49 refactor/date-picker
  app/src/main/java/com/example/tudeeapp/MainActivity.kt
  app/src/main/java/com/example/tudeeapp/TudeeApplication.kt
  app/src/main/java/com/example/tudeeapp/di/ViewModelModule.kt
  app/src/main/java/com/example/tudeeapp/presentation/TudeeAppScaffold.kt
  app/src/main/java/com/example/tudeeapp/presentation/common/components/TudeeDatePickerDialog.kt
  app/src/main/java/com/example/tudeeapp/presentation/navigation/Destinations.kt
  app/src/main/java/com/example/tudeeapp/presentation/navigation/TudeeNavGraph.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/HomeScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/task/TasksScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/task/TasksViewModel.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/taskDetails/TaskDetailsScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/taskManagement/TaskManagementBottomSheet.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/taskManagement/TaskManagementViewModel.kt
Labels: fix

#48 Refactor/onboarding screen
  app/src/main/java/com/example/tudeeapp/di/ViewModelModule.kt
  app/src/main/java/com/example/tudeeapp/presentation/navigation/Destinations.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/onBoarding/OnBoardingScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/onBoarding/OnBoardingUIState.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/onBoarding/OnBoardingViewModel.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/onBoarding/OnboardingViewModel.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/onBoarding/components/BottomSection.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/onBoarding/components/OnBoardingImage.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/onBoarding/components/OnBoardingPage.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: fix

#53 refactor navigation logic in OnBoarding and Splash screens
  app/src/main/java/com/example/tudeeapp/presentation/screen/onBoarding/OnBoardingScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/onBoarding/OnBoardingViewModel.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/splash/SplashScreen.kt
Labels: enhancement

#55 Refactor/category form view model
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoriesForm/CategoryForm.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoriesForm/CategoryFormViewModel.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#51 Fix refresh CategoryDetailsScreen after editing category
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoryDetails/CategoryDetailsScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoryDetails/CategoryDetailsUiState.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoryDetails/CategoryDetailsViewModel.kt
Labels: fix

#60 refactor/categories-view-model
  app/src/main/java/com/example/tudeeapp/presentation/screen/categories/CategoriesInteractionListener.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categories/CategoriesScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categories/CategoriesViewModel.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categories/CategoryUiState.kt
  app/src/test/java/com/example/tudeeapp/presentation/screen/categories/CategoriesViewModelTest.kt
Labels: enhancement

#58 refactor/task-management
  app/src/main/java/com/example/tudeeapp/presentation/screen/taskForm/InteractionListener.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/taskForm/TaskFormBottomSheet.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/taskForm/TaskFormViewModel.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/taskForm/components/CategoryGrid.kt
Labels: enhancement

#67 Bugfix/fix lazy lists
  app/src/main/java/com/example/tudeeapp/data/source/local/room/dao/CategoryDao.kt
  app/src/main/java/com/example/tudeeapp/data/source/local/room/dao/TaskDao.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categories/CategoriesScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/HomeScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/task/TasksScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/taskForm/TaskFormViewModel.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/taskForm/components/CategoryGrid.kt
Labels: bug

#66 Refactor/category form
  app/src/main/java/com/example/tudeeapp/presentation/common/extentions/Extensions.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoriesForm/CategoryForm.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoriesForm/CategoryFormInteractionListener.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoriesForm/CategoryFormViewModel.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoriesForm/components/CategoriesBottomSheetButtons.kt
Labels: enhancement

#78 refactor/Create CategoryInteractionListener interface
  app/src/main/java/com/example/tudeeapp/presentation/navigation/Screens.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoryDetails/CategoryDetailsScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoryDetails/CategoryDetailsViewModel.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoryDetails/CategoryInteractionListener.kt
Labels: enhancement

#84 Handle text overflow for empty section title
  app/src/main/java/com/example/tudeeapp/presentation/common/components/EmptyTaskSection.kt
Labels: fix

#79 bugfix/fix-tasks-order-and-local-data-time
  app/src/main/java/com/example/tudeeapp/data/exception/DataException.kt
  app/src/main/java/com/example/tudeeapp/data/mapper/TasksMapper.kt
  app/src/main/java/com/example/tudeeapp/data/source/local/room/Converters.kt
  app/src/main/java/com/example/tudeeapp/data/source/local/room/TudeeDatabase.kt
  app/src/main/java/com/example/tudeeapp/data/source/local/room/TudeeDbMigrations.kt
  app/src/main/java/com/example/tudeeapp/data/source/local/room/entity/CategoryEntity.kt
  app/src/main/java/com/example/tudeeapp/data/source/local/room/entity/TaskEntity.kt
  app/src/main/java/com/example/tudeeapp/domain/models/Task.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoryDetails/CategoryDetailsUiState.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoryDetails/CategoryDetailsViewModel.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/HomeViewModel.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/task/TaskUiState.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/task/TasksViewModel.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/taskDetails/TaskDetailsUiState.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/taskForm/TaskFormViewModel.kt
Labels: fix

#90 fix Task form
  app/src/main/java/com/example/tudeeapp/data/TaskServicesImpl.kt
  app/src/main/java/com/example/tudeeapp/data/source/local/room/dao/TaskDao.kt
  app/src/main/java/com/example/tudeeapp/data/source/local/sharedPreferences/AppPreferences.kt
  app/src/main/java/com/example/tudeeapp/presentation/TudeeAppScaffold.kt
  app/src/main/java/com/example/tudeeapp/presentation/common/components/ConfirmationDialogBox.kt
  app/src/main/java/com/example/tudeeapp/presentation/common/components/TudeeBottomSheet.kt
  app/src/main/java/com/example/tudeeapp/presentation/common/components/TudeeDeleteBottomSheet.kt
  app/src/main/java/com/example/tudeeapp/presentation/common/extentions/DateTimeExtentions.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoriesForm/CategoryForm.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/categoryDetails/CategoryDetailsScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/HomeScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/HomeUiState.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/home/HomeViewModel.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/task/TasksScreen.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/taskForm/TaskFormBottomSheet.kt
  app/src/main/java/com/example/tudeeapp/presentation/screen/taskForm/TaskFormViewModel.kt
Labels: fix
